// Code generated by 'go generate'; DO NOT EDIT.

package native

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modwimgapi = windows.NewLazySystemDLL("wimgapi.dll")

	procWIMApplyImage              = modwimgapi.NewProc("WIMApplyImage")
	procWIMCloseHandle             = modwimgapi.NewProc("WIMCloseHandle")
	procWIMCreateFile              = modwimgapi.NewProc("WIMCreateFile")
	procWIMGetAttributes           = modwimgapi.NewProc("WIMGetAttributes")
	procWIMGetImageCount           = modwimgapi.NewProc("WIMGetImageCount")
	procWIMGetImageInformation     = modwimgapi.NewProc("WIMGetImageInformation")
	procWIMGetMessagecallbackCount = modwimgapi.NewProc("WIMGetMessagecallbackCount")
)

func WIMApplyImage(hImage syscall.Handle, pszPath *uint16, dwApplyFlags uint32) (err error) {
	r1, _, e1 := syscall.Syscall(procWIMApplyImage.Addr(), 3, uintptr(hImage), uintptr(unsafe.Pointer(pszPath)), uintptr(dwApplyFlags))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func WIMCloseHandle(hObject syscall.Handle) (err error) {
	r1, _, e1 := syscall.Syscall(procWIMCloseHandle.Addr(), 1, uintptr(hObject), 0, 0)
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func WIMCreateFile(pszWimPath *uint16, dwDesiredAccess uint32, dwCreationDisposition uint32, dwFlagsAndAttributes uint32, dwCompressionType uint32, pdwCreationResult *uint32) (handle syscall.Handle, err error) {
	r0, _, e1 := syscall.Syscall6(procWIMCreateFile.Addr(), 6, uintptr(unsafe.Pointer(pszWimPath)), uintptr(dwDesiredAccess), uintptr(dwCreationDisposition), uintptr(dwFlagsAndAttributes), uintptr(dwCompressionType), uintptr(unsafe.Pointer(pdwCreationResult)))
	handle = syscall.Handle(r0)
	if handle == 0 {
		err = errnoErr(e1)
	}
	return
}

func WIMGetAttributesR(hImage syscall.Handle, pWimInfo *WimInfo, cbWimInfo uint32) (err error) {
	r1, _, e1 := syscall.Syscall(procWIMGetAttributes.Addr(), 3, uintptr(hImage), uintptr(unsafe.Pointer(pWimInfo)), uintptr(cbWimInfo))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func WIMGetImageCount(hWim syscall.Handle) (n uint32, err error) {
	r0, _, e1 := syscall.Syscall(procWIMGetImageCount.Addr(), 1, uintptr(hWim), 0, 0)
	n = uint32(r0)
	if n == 0 {
		err = errnoErr(e1)
	}
	return
}

func WIMGetImageInformationR(hImage syscall.Handle, ppvImageInfo **uint16, pcbImageInfo *uint32) (err error) {
	r1, _, e1 := syscall.Syscall(procWIMGetImageInformation.Addr(), 3, uintptr(hImage), uintptr(unsafe.Pointer(ppvImageInfo)), uintptr(unsafe.Pointer(pcbImageInfo)))
	if r1 == 0 {
		err = errnoErr(e1)
	}
	return
}

func WIMGetMessagecallbackCount(hWim syscall.Handle) (n uint32, err error) {
	r0, _, e1 := syscall.Syscall(procWIMGetMessagecallbackCount.Addr(), 1, uintptr(hWim), 0, 0)
	n = uint32(r0)
	if n == 0 {
		err = errnoErr(e1)
	}
	return
}
